### ISSUE TITLE
Bad request error

### ISSUE THREAD

**Issue by nseries100** [hp-net/homebridge-nibe#124]
Hello,

could you please help me with this type of error in homebridge? Everything was ok for some time but today I checked homebridge for update some plugins and this error was there in main log. 

Thank you

```
[14/10/2022, 06:33:30] [Nibe] error from /oauth/token
[14/10/2022, 06:33:30] [Nibe] Error: Error: Bad Request: {
 "error": "invalid_request"
}
    at NibeFetcher.checkError (/usr/lib/node_modules/homebridge-nibe/dist/nibe/uplink/nibe-fetcher.js:337:28)
    at NibeFetcher.postTokenRequest (/usr/lib/node_modules/homebridge-nibe/dist/nibe/uplink/nibe-fetcher.js:238:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at NibeFetcher.getToken (/usr/lib/node_modules/homebridge-nibe/dist/nibe/uplink/nibe-fetcher.js:211:16)
    at NibeFetcher.fetch (/usr/lib/node_modules/homebridge-nibe/dist/nibe/uplink/nibe-fetcher.js:146:35)
```

**Comment by hpruszyn** [comment]
Hi, try to generate AuthCode again. It is described in step 3 of setup instruction.

**Comment by hpruszyn** [comment]
@nseries100 did it helped?

**Comment by nseries100** [comment]
Thank you very much.

Its working again from now!
