### ISSUE TITLE
Bad request

### ISSUE THREAD

**Issue by MKSoftware89** [hp-net/homebridge-nibe#184]
**Describe the bug**
I usually try to install the add on and no matter how often I try another token I got this problem.

**Screenshots & Logfiles**
[07/08/2023, 15:36:21] [Nibe] error from /oauth/token
[07/08/2023, 15:36:21] [Nibe] Error: Error: Bad Request: {
 "error": "invalid_request"
}
    at NibeFetcher.checkError (/var/lib/homebridge/node_modules/homebridge-nibe/dist/nibe/uplink/nibe-fetcher.js:337:28)
    at NibeFetcher.postTokenRequest (/var/lib/homebridge/node_modules/homebridge-nibe/dist/nibe/uplink/nibe-fetcher.js:238:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at NibeFetcher.getToken (/var/lib/homebridge/node_modules/homebridge-nibe/dist/nibe/uplink/nibe-fetcher.js:211:16)
    at NibeFetcher.fetch (/var/lib/homebridge/node_modules/homebridge-nibe/dist/nibe/uplink/nibe-fetcher.js:146:35)

**Versions**
Plugin version: v1.2.2
Node version: v18.16.0
Operating system: Raspbian GNU/Linux Bullseye (11)

Thanks for your help :)

**Comment by hpruszyn** [comment]
@MKSoftware89 please try the new version of the plugin that uses Nibe MyUplink and offers a more straightforward configuration.
