### ISSUE TITLE
Token Error

### ISSUE THREAD

**Issue by b-a-k-u-a-n** [hp-net/homebridge-nibe#215]
Startup log (values in HomeKit show). Not sure what is wrong. Thanks for help.

[17/07/2024, 19:41:46] [Nibe] error from /oauth/token
[17/07/2024, 19:41:46] [Nibe] Error: Error: Bad Request: {
 "error": "invalid_request"
}
    at NibeFetcher.checkError (/var/lib/homebridge/node_modules/homebridge-nibe/dist/nibe/uplink/nibe-fetcher.js:337:28)
    at NibeFetcher.postTokenRequest (/var/lib/homebridge/node_modules/homebridge-nibe/dist/nibe/uplink/nibe-fetcher.js:238:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at NibeFetcher.getToken (/var/lib/homebridge/node_modules/homebridge-nibe/dist/nibe/uplink/nibe-fetcher.js:211:16)
    at NibeFetcher.fetch (/var/lib/homebridge/node_modules/homebridge-nibe/dist/nibe/uplink/nibe-fetcher.js:146:35)

**Comment by hpruszyn** [comment]
@b-a-k-u-a-n please try the new version of the plugin that uses Nibe MyUplink and offers a more straightforward configuration.
